In [1]:
import os
import time

import numpy as np

## Power Iteration (naive version)

In [2]:
n = 10
A = np.random.rand(n, n)
A = A + A.T # make A symmetric
A

array([[1.86499773, 1.03084908, 0.79445385, 1.37315888, 1.0358633 ,
        1.40337002, 1.79362058, 1.77484352, 0.21759045, 0.96175826],
       [1.03084908, 1.07546615, 1.09368951, 0.95276913, 1.56635058,
        1.44762651, 1.69619211, 0.88272785, 1.03172841, 0.76931197],
       [0.79445385, 1.09368951, 1.67294312, 0.12186061, 0.54345833,
        0.52911833, 0.24780724, 0.46647832, 0.86452259, 0.94532059],
       [1.37315888, 0.95276913, 0.12186061, 1.98023059, 1.18915405,
        1.79798394, 0.49838315, 0.39772726, 1.34696042, 1.73379659],
       [1.0358633 , 1.56635058, 0.54345833, 1.18915405, 0.40116623,
        0.88074901, 1.21412068, 1.26395549, 1.58728916, 1.6174794 ],
       [1.40337002, 1.44762651, 0.52911833, 1.79798394, 0.88074901,
        0.27077348, 1.25938715, 1.08052315, 0.43028142, 1.09485715],
       [1.79362058, 1.69619211, 0.24780724, 0.49838315, 1.21412068,
        1.25938715, 0.81573363, 0.83426988, 1.4914469 , 1.83891134],
       [1.77484352, 0.88272785, 0.4664783

In [3]:
w = np.random.rand(n, 1)
prev_w = w
step = 1
while True:
    m = A @ w
    q = m / np.linalg.norm(m, ord=2)
    w = q
    
    # check convergence
    if np.allclose(prev_w, w):
        print(f"step: {step}")
        break
        
    prev_w = w
    step += 1
w 

step: 9


array([[0.35560133],
       [0.32874916],
       [0.19652408],
       [0.34079338],
       [0.32804731],
       [0.30217417],
       [0.3467013 ],
       [0.26493572],
       [0.27886507],
       [0.37898169]])

In [4]:
# check for the first eigenvector
U, S, V = np.linalg.svd(A)
U[:, 0]

array([-0.35560147, -0.32874921, -0.19652401, -0.34079324, -0.32804725,
       -0.30217427, -0.34670113, -0.26493566, -0.27886525, -0.3789817 ])

## Orthogonal/Subspace/Simultaneous Iteration 

In [5]:
n = 10
k = 5 # Condition: k < n
A = np.random.rand(n, n)
A = A + A.T # make A symmetric
A

array([[0.53635343, 1.0995942 , 0.78298528, 0.44229695, 0.71542666,
        1.61019761, 0.56817193, 0.56420826, 1.07705562, 0.96010582],
       [1.0995942 , 1.96838227, 0.22723578, 1.2852785 , 0.87481116,
        1.32723255, 1.35853843, 0.5122554 , 0.23478604, 0.80805871],
       [0.78298528, 0.22723578, 1.43758949, 1.614269  , 0.87205978,
        1.06240182, 1.9143086 , 0.97744638, 0.59039953, 1.07525904],
       [0.44229695, 1.2852785 , 1.614269  , 0.05859349, 0.74785264,
        0.72295798, 1.21352639, 1.44842409, 1.37809892, 1.34577067],
       [0.71542666, 0.87481116, 0.87205978, 0.74785264, 1.9066172 ,
        1.57445473, 0.97870504, 0.4390443 , 1.34751752, 0.90618566],
       [1.61019761, 1.32723255, 1.06240182, 0.72295798, 1.57445473,
        1.17369225, 1.1744562 , 0.78269922, 0.77670078, 1.71834375],
       [0.56817193, 1.35853843, 1.9143086 , 1.21352639, 0.97870504,
        1.1744562 , 1.98984588, 1.64528258, 0.48491928, 0.37954049],
       [0.56420826, 0.5122554 , 0.9774463

In [6]:
W = np.random.rand(n, k)
prev_W = W
step = 1
while True:
    M = A @ W
    Q, R = np.linalg.qr(M)
    W = Q
    
    # check convergence
    if step != 1 and np.allclose(prev_W, W):
        print(f"step: {step}")
        break
        
    prev_W = W
    step += 1
W 

step: 1341


array([[-0.25735105, -0.25350843,  0.29268086, -0.09610868, -0.25215006],
       [-0.29808414, -0.10066142, -0.30009771, -0.75056101, -0.07673818],
       [-0.32972443,  0.38427924, -0.34658749,  0.24437909, -0.11696359],
       [-0.3128189 ,  0.14621441,  0.70029291,  0.12469   ,  0.2776717 ],
       [-0.31915077, -0.2937494 ,  0.10679183, -0.0146923 , -0.26531032],
       [-0.36335942, -0.29057489, -0.01158965, -0.13931453,  0.35301818],
       [-0.36274713,  0.59483957,  0.08232304, -0.2341962 ,  0.20676453],
       [-0.28675955,  0.2638967 , -0.08541311,  0.21774622, -0.56093955],
       [-0.27391111, -0.15805882, -0.43322372,  0.3580297 ,  0.50857986],
       [-0.34001666, -0.37063584, -0.02126359,  0.31950212, -0.16935146]])

In [7]:
U, S, V = np.linalg.svd(A)
U[:k]

array([[-0.25735105, -0.25350843,  0.29268083,  0.09610878,  0.25215006,
         0.09187944,  0.33472863,  0.18419607, -0.38864174,  0.63684348],
       [-0.29808414, -0.10066142, -0.30009797,  0.75056091,  0.07673818,
         0.29567997, -0.03711958, -0.2208086 , -0.20403855, -0.25006245],
       [-0.32972443,  0.38427924, -0.34658741, -0.24437921,  0.11696359,
        -0.09587964, -0.13844269,  0.50285732, -0.48443403, -0.18489367],
       [-0.3128189 ,  0.14621441,  0.70029295, -0.12468976, -0.2776717 ,
         0.21216828, -0.21903388, -0.22040364, -0.27682714, -0.28196471],
       [-0.31915077, -0.2937494 ,  0.10679182,  0.01469234,  0.26531032,
        -0.78862428,  0.03600558, -0.2068629 , -0.00810884, -0.25251035]])

## Orthogonal/Subspace/Simultaneous Iteration  (SVD version)

A quick note, this version is trying to solve the following optimization problem: 
\begin{equation}
    \mathrm{Tr}(W^{\top}AW)
\end{equation}
, where $A$ is a positive semi-definite.

In [8]:
n = 50
k = 5 # Condition: k < n
A = np.random.rand(n, n)
A = A + A.T # make A symmetric
A

array([[0.55373903, 0.7967697 , 0.93933074, ..., 0.15810815, 0.62133368,
        1.58148596],
       [0.7967697 , 1.34386004, 0.7350697 , ..., 1.06869878, 0.95665333,
        0.75774177],
       [0.93933074, 0.7350697 , 0.35596531, ..., 1.04328974, 1.10822284,
        0.93416954],
       ...,
       [0.15810815, 1.06869878, 1.04328974, ..., 0.20297079, 0.75046873,
        1.17491218],
       [0.62133368, 0.95665333, 1.10822284, ..., 0.75046873, 1.52146115,
        1.15210532],
       [1.58148596, 0.75774177, 0.93416954, ..., 1.17491218, 1.15210532,
        0.26301273]])

In [9]:
loss = lambda W: np.trace(W.T @ A @ W)
W = np.random.rand(n, k)
prev_loss = 0
curr_loss = 0
step = 0
while True:
    M = A @ W
    U, S, V = np.linalg.svd(M, full_matrices=False)
    W = U @ V
    curr_loss = loss(W)
    print(f"step: {step}\t loss: {curr_loss}")
    # check convergence
    if step != 0 and np.allclose(prev_loss, curr_loss):
        break
    prev_loss = curr_loss
    step += 1
W 

step: 0	 loss: 47.00954792432825
step: 1	 loss: 45.79466900257554
step: 2	 loss: 45.53514087923723
step: 3	 loss: 45.807936857805785
step: 4	 loss: 46.35664578536742
step: 5	 loss: 47.0298455516151
step: 6	 loss: 47.73145214407699
step: 7	 loss: 48.397692282606826
step: 8	 loss: 48.988946561800475
step: 9	 loss: 49.485990100589554
step: 10	 loss: 49.88566228666839
step: 11	 loss: 50.19551104979241
step: 12	 loss: 50.42862513334469
step: 13	 loss: 50.5996750007194
step: 14	 loss: 50.72246394155917
step: 15	 loss: 50.80876090808852
step: 16	 loss: 50.86799249061633
step: 17	 loss: 50.90740315919703
step: 18	 loss: 50.93240974344658
step: 19	 loss: 50.946991842352304
step: 20	 loss: 50.95404295714195
step: 21	 loss: 50.95565650624776
step: 22	 loss: 50.953345813839086
step: 23	 loss: 50.94820740757858
step: 24	 loss: 50.941039550161356
step: 25	 loss: 50.93242710054937
step: 26	 loss: 50.9228018002401
step: 27	 loss: 50.91248495693725
step: 28	 loss: 50.901717663025394
step: 29	 loss: 50.

array([[ 3.93873399e-02,  1.15434852e-01,  2.55556385e-01,
         1.25898970e-01, -2.42426825e-01],
       [-4.84055467e-02,  6.99000162e-02,  1.81454037e-01,
        -3.16888558e-02,  1.25442485e-01],
       [ 1.38989730e-01, -1.80058432e-01,  1.68097544e-01,
         2.00756430e-01, -2.94689089e-02],
       [ 4.33150283e-02,  1.52592506e-01,  1.80183565e-01,
        -5.20910529e-02,  8.82016720e-03],
       [-2.03119774e-02,  4.90022942e-02,  1.07690506e-01,
         9.47467886e-02,  7.24132407e-02],
       [ 2.49038050e-01, -2.76081889e-01,  1.42238411e-01,
         1.04999095e-01,  9.85500603e-02],
       [ 5.00346990e-02,  1.44516934e-01,  1.16205612e-01,
        -9.42899253e-03,  2.71713916e-02],
       [-2.59186541e-02,  2.33194806e-01, -1.07980616e-01,
         1.84468364e-01,  2.49062087e-02],
       [-2.39961394e-01,  1.74020319e-02,  1.98939477e-01,
         7.47183598e-02,  2.79212474e-01],
       [ 1.70157760e-01,  1.65096626e-01,  3.80808330e-02,
        -1.91767132e-01

## Generalized Power Iteration Method (GPI)

In [10]:
n = 50
k = 40 # k < n 
# A = np.random.randint(-100, 100, size=(n, n))
A = np.random.rand(n, n)
A = (A + A.T) / 2 # symmetric 
B = np.random.rand(n, k)
# B = np.zeros(shape=(n, k))

In [11]:
alpha = 1e2
A_hat = alpha * np.eye(n) - A
W = np.linalg.svd(np.random.rand(n, n))[0][:, :k] # shape: (m, k)
loss_func = lambda W: np.trace(W.T @ A @ W) + 2 * np.trace(W.T @ B)
# loss_func = lambda W: np.trace(W.T @ A_hat @ W - 2 * W.T @ B)
prev_loss = 0
curr_loss = 0
step = 1
converged = False

while not converged:
    M = 2 * A_hat @ W + 2 * B
    U, S, V = np.linalg.svd(M, full_matrices=False)
    W = U @ V.T
    curr_loss = loss_func(W)
    
    # check convergence
    if step != 1:
        if False:#np.allclose(prev_loss, curr_loss):
            converged = True
        if step > 800:
            converged = True
    print(f"step: {step} - loss: {curr_loss}")
#     print(W)
    
    prev_loss = curr_loss
    step += 1

step: 1 - loss: 36.28119680418079
step: 2 - loss: 33.27565553506631
step: 3 - loss: 17.609741608765844
step: 4 - loss: 30.65872062981184
step: 5 - loss: 30.12626673734856
step: 6 - loss: 30.064735805717255
step: 7 - loss: 17.006237047125133
step: 8 - loss: 16.736349652315837
step: 9 - loss: 25.06356664885461
step: 10 - loss: 13.089227239680742
step: 11 - loss: 14.213087722323586
step: 12 - loss: 10.498107113782659
step: 13 - loss: 6.002299585488695
step: 14 - loss: 5.889242084616445
step: 15 - loss: 7.162755667189609
step: 16 - loss: -2.235040539411363
step: 17 - loss: -0.7782592110227078
step: 18 - loss: 1.4442749658827467
step: 19 - loss: 3.538187576075382
step: 20 - loss: 3.7132141386122766
step: 21 - loss: -3.2056611933338752
step: 22 - loss: 6.859483067433509
step: 23 - loss: -3.9974146722506694
step: 24 - loss: 0.7422850503844565
step: 25 - loss: 4.8000978149503
step: 26 - loss: -9.194827786205535
step: 27 - loss: -10.43338823457044
step: 28 - loss: -5.68870490697361
step: 29 - l

step: 304 - loss: -5.84864147429645
step: 305 - loss: -10.080106953126956
step: 306 - loss: -9.844132615777243
step: 307 - loss: -14.285644954650294
step: 308 - loss: -5.715734896744335
step: 309 - loss: -10.152021356268591
step: 310 - loss: -18.17232202081193
step: 311 - loss: -11.980423049042656
step: 312 - loss: -8.32591085339671
step: 313 - loss: -13.41725594289482
step: 314 - loss: -3.3384674992503793
step: 315 - loss: -12.977615528967513
step: 316 - loss: -9.697937498129717
step: 317 - loss: -19.295108194317283
step: 318 - loss: -8.247335748120665
step: 319 - loss: -9.950882105784832
step: 320 - loss: -12.278670446247173
step: 321 - loss: -13.100994104793934
step: 322 - loss: -14.074253990244031
step: 323 - loss: -9.307113591885475
step: 324 - loss: -9.682828928384364
step: 325 - loss: -10.494852348878817
step: 326 - loss: -11.222668549002162
step: 327 - loss: -12.644216886075903
step: 328 - loss: -15.622394939532398
step: 329 - loss: -16.117631795665577
step: 330 - loss: -18.651

step: 527 - loss: -14.76201173418308
step: 528 - loss: -12.71714614734686
step: 529 - loss: -8.493283755800782
step: 530 - loss: -9.625476140127352
step: 531 - loss: -13.07744746647069
step: 532 - loss: -5.1036361426290355
step: 533 - loss: -2.1048005395752565
step: 534 - loss: -5.968771926363183
step: 535 - loss: -9.329001304541967
step: 536 - loss: -14.328665935209962
step: 537 - loss: -11.94855154186599
step: 538 - loss: -12.752091786350803
step: 539 - loss: -18.81932385635905
step: 540 - loss: -9.867270682432643
step: 541 - loss: -11.143687101927737
step: 542 - loss: -8.40631921786727
step: 543 - loss: -3.4220296843842437
step: 544 - loss: -10.725670500237378
step: 545 - loss: -11.295045025546845
step: 546 - loss: -18.03087245780415
step: 547 - loss: -13.536288812135567
step: 548 - loss: -14.960224534875733
step: 549 - loss: -12.644375757406715
step: 550 - loss: -13.488655907169907
step: 551 - loss: -16.114628930120688
step: 552 - loss: -11.502015863961931
step: 553 - loss: -15.137

step: 775 - loss: -7.081251203610383
step: 776 - loss: -9.230867280274571
step: 777 - loss: -14.494563352363405
step: 778 - loss: -11.232169176822651
step: 779 - loss: -5.3534398248969435
step: 780 - loss: -2.775694084833882
step: 781 - loss: -3.4391014669595936
step: 782 - loss: -10.637391577313071
step: 783 - loss: -7.13904277826725
step: 784 - loss: -7.775506060710718
step: 785 - loss: -19.128030421946793
step: 786 - loss: -8.848970081591505
step: 787 - loss: -10.095369582877323
step: 788 - loss: -10.292926216688114
step: 789 - loss: -7.521958964566379
step: 790 - loss: -5.255040057982804
step: 791 - loss: -12.197760537871483
step: 792 - loss: -5.484234306235511
step: 793 - loss: -9.466287174871841
step: 794 - loss: -18.967255071939825
step: 795 - loss: -14.579304589794567
step: 796 - loss: -17.39341516812394
step: 797 - loss: -7.211859504872763
step: 798 - loss: -15.431558877134071
step: 799 - loss: -13.700570973044009
step: 800 - loss: -7.686057147356033
step: 801 - loss: -17.0867